import { CompanyStockItem } from "@/app/lib/company-stock";

const CREATED_AT = Date.UTC(2026, 2, 16);

function row(
  id: string,
  category: CompanyStockItem["category"],
  name: string,
  openingStock = "",
  received = "",
  issued = "",
  damaged = "",
  balance = "",
): CompanyStockItem {
  return {
    id,
    category,
    name,
    openingStock,
    received,
    issued,
    damaged,
    balance,
    createdAt: CREATED_AT,
  };
}

export const COMPANY_STOCK_SHEET: CompanyStockItem[] = [
  row("cs-sheet-001", "linen", "Bedsheets", "512", "", "104", "", "408"),
  row("cs-sheet-002", "linen", "Pillowcases", "646", "", "208", "", "438"),
  row("cs-sheet-003", "linen", "Small pillow cases", "116", "", "104", "", "12"),
  row("cs-sheet-004", "linen", "Small pillow", "108", "", "104", "", "4"),
  row("cs-sheet-005", "linen", "Big pillow", "212", "", "208", "", "4"),
  row("cs-sheet-006", "linen", "Bed runner", "153", "", "53", "", "100"),
  row("cs-sheet-007", "linen", "Towels L", "236", "", "85", "", "151"),
  row("cs-sheet-008", "linen", "Towels XXL", "15", "", "0", "", "15"),
  row("cs-sheet-009", "linen", "Face towels ORANGE", "60", "", "52", "", "8"),
  row("cs-sheet-010", "linen", "Hand towels Orange", "59", "", "0", "", "59"),
  row("cs-sheet-011", "linen", "Face towels", "200", "", "0", "", "200"),
  row("cs-sheet-012", "linen", "Brown towels", "11", "", "0", "", "11"),
  row("cs-sheet-013", "linen", "Duvet cover", "137", "", "52", "", "85"),
  row("cs-sheet-014", "linen", "Duvet", "120", "", "52", "", "68"),
  row("cs-sheet-015", "linen", "Bed cover", "54", "", "52", "", "2"),
  row("cs-sheet-016", "linen", "White(lace) curtains", "142", "", "", "", "142"),
  row("cs-sheet-017", "linen", "Gray curtains", "132", "", "", "", "132"),
  row("cs-sheet-018", "linen", "Net white", "25", "", "", "", "25"),
  row("cs-sheet-019", "linen", "Napkin", "58", "", "", "", "58"),
  row("cs-sheet-020", "linen", "Table mat", "60", "", "30", "", "30"),
  row("cs-sheet-021", "linen", "Room carpet", "149", "", "52", "", "97"),
  row("cs-sheet-022", "linen", "Room door mat", "100", "", "52", "", "48"),
  row("cs-sheet-023", "linen", "Sleepers", "53", "", "53", "", "0"),
  row("cs-sheet-024", "linen", "Heater Jags", "31", "", "30", "", "1"),
  row("cs-sheet-025", "linen", "Dustbeen", "105", "", "52", "", "53"),
  row("cs-sheet-026", "linen", "Extension phone", "57", "", "57", "", "0"),
  row("cs-sheet-027", "linen", "Plastic mat", "3", "", "3", "", "0"),
  row("cs-sheet-028", "linen", 'TV "Inch55"', "31", "", "", "", "31"),
  row("cs-sheet-029", "linen", 'TV "Inch44"', "25", "", "", "", "25"),
  row("cs-sheet-030", "linen", 'TV "Inch85" restaurant', "2", "", "2", "", "0"),
  row("cs-sheet-031", "linen", 'TV Inch"72" reception', "1", "", "", "", "1"),
  row("cs-sheet-032", "linen", "Office Table", "53", "", "53", "", "0"),
  row("cs-sheet-033", "linen", "Round Table", "52", "", "52", "", "0"),
  row("cs-sheet-034", "linen", "Ladgage Table", "53", "", "53", "", "0"),
  row("cs-sheet-035", "linen", 'Chairs "room', "112", "", "112", "0", "0"),
  row("cs-sheet-036", "linen", 'Chairs "restaurant', "151", "", "151", "", "0"),
  row("cs-sheet-037", "linen", 'Tables big size (restaurant)', "10", "", "10", "", "0"),
  row("cs-sheet-038", "linen", 'Tables small size "R"', "6", "", "", "", "6"),
  row("cs-sheet-039", "linen", 'Table min size "BAR"', "2", "", "", "", "2"),
  row("cs-sheet-040", "linen", "Chairs (BAR)", "9", "", "", "", "9"),
  row("cs-sheet-041", "linen", "Serving Tray", "26", "", "", "", "26"),
  row("cs-sheet-042", "linen", "Min Fridge", "30", "", "", "", "30"),
  row("cs-sheet-043", "linen", "Fridge/Bar", "1", "", "", "", "1"),
  row("cs-sheet-044", "linen", "Kitchen Fridge", "1", "", "", "", "1"),
  row("cs-sheet-045", "linen", "Freezer Kitchen", "1", "", "", "", "1"),
  row("cs-sheet-046", "linen", "Fan total", "7", "", "", "", "7"),
  row("cs-sheet-047", "linen", 'Bed & matress 5"6', "23", "", "", "", "23"),
  row("cs-sheet-048", "linen", 'Bed & matress 6"6', "30", "", "", "", "30"),
  row("cs-sheet-049", "linen", "A/C REMOTE", "38", "", "", "", "38"),
  row("cs-sheet-050", "linen", "TV REMOTE", "52", "", "", "", "52"),

  row("cs-sheet-051", "cutleries", "Teaspoon", "36", "", "36", "", "0"),
  row("cs-sheet-052", "cutleries", "Table spoon", "47", "", "47", "", "47"),
  row("cs-sheet-053", "cutleries", "Soup spoon", "47", "", "6", "", "41"),
  row("cs-sheet-054", "cutleries", "Table knife", "49", "", "49", "", "0"),
  row("cs-sheet-055", "cutleries", "Starter knife", "44", "", "44", "", "0"),
  row("cs-sheet-056", "cutleries", "Fork", "48", "", "48", "", "0"),

  row("cs-sheet-057", "cups-pots", "Teacups(big)", "44", "", "", "", "44"),
  row("cs-sheet-058", "cups-pots", "Tea, coffee tray (room)", "31", "", "", "", "31"),
  row("cs-sheet-059", "cups-pots", "icecream scope spoon", "1", "", "", "", "1"),
  row("cs-sheet-060", "cups-pots", "Tea souce", "48", "", "", "", "48"),
  row("cs-sheet-061", "cups-pots", "Tea cups small size", "24", "", "", "", "24"),
  row("cs-sheet-062", "cups-pots", "Coffee cups & souces", "36", "", "", "", "36"),
  row("cs-sheet-063", "cups-pots", "Tea pots silver", "9", "", "", "", "9"),
  row("cs-sheet-064", "cups-pots", "sugar,coffee,tea bag pot", "10", "", "", "", "10"),
  row("cs-sheet-065", "cups-pots", "Coffee pot/jag", "18", "", "", "", "18"),
  row("cs-sheet-066", "cups-pots", "Salt & black papet shacker", "19", "", "", "", "19"),
  row("cs-sheet-067", "cups-pots", "Tooothpick holder", "10", "", "", "", "10"),
  row("cs-sheet-068", "cups-pots", "Straws", "24", "", "", "", "24"),

  row("cs-sheet-069", "glasses", "Juice glass (small size)", "48", "", "", "", "48"),
  row("cs-sheet-070", "glasses", "Juice/water glass", "120", "", "", "", "120"),
  row("cs-sheet-071", "glasses", "Icecream glass", "34", "", "", "", "34"),
  row("cs-sheet-072", "glasses", "Cocktail glass", "12", "", "", "", "12"),
  row("cs-sheet-073", "glasses", "Red wine glass", "12", "", "", "", "12"),
  row("cs-sheet-074", "glasses", "Whisky glass", "50", "", "", "", "50"),
  row("cs-sheet-075", "glasses", "champagne glass", "23", "", "", "", "23"),
  row("cs-sheet-076", "glasses", "Juice glass with straws", "34", "", "", "", "34"),
  row("cs-sheet-077", "glasses", "Mocktail glass", "12", "", "", "", "12"),
  row("cs-sheet-078", "glasses", "Milk glass", "1", "", "", "", "1"),
  row("cs-sheet-079", "glasses", "Mag glass", "24", "", "", "", "24"),
  row("cs-sheet-080", "glasses", "Juice tacker", "7", "", "", "", "7"),
  row("cs-sheet-081", "glasses", "wine oppener", "4", "", "", "", "4"),
  row("cs-sheet-082", "glasses", "Ice cubes jag", "4", "", "", "", "4"),
  row("cs-sheet-083", "glasses", "Tot measure", "1", "", "", "", "1"),

  row("cs-sheet-084", "plates-bowls", "Soup bowls", "47", "", "", "", "47"),
  row("cs-sheet-085", "plates-bowls", 'Dinner plate "standard', "36", "", "", "", "36"),
  row("cs-sheet-086", "plates-bowls", "souce bowls", "30", "", "", "", "30"),
  row("cs-sheet-087", "plates-bowls", "Salad plate", "24", "", "", "", "24"),
  row("cs-sheet-088", "plates-bowls", "Paster plate", "2", "", "", "", "2"),
  row("cs-sheet-089", "plates-bowls", "Square dinner plate", "36", "", "", "", "36"),
  row("cs-sheet-090", "plates-bowls", 'Platter plate "salad', "12", "", "", "", "12"),
  row("cs-sheet-091", "plates-bowls", "Fish plate", "10", "", "", "", "10"),
  row("cs-sheet-092", "plates-bowls", "Side plates", "48", "", "", "", "48"),
  row("cs-sheet-093", "plates-bowls", 'Salad bowl "big', "1", "", "", "", "1"),
  row("cs-sheet-094", "plates-bowls", "Big juice jag", "2", "", "", "", "2"),

  row("cs-sheet-095", "others", "Souce pot & lead big size", "6", "", "", "", "6"),
  row("cs-sheet-096", "others", "Souce pot smal size", "6", "", "", "", "6"),
  row("cs-sheet-097", "others", "Fryer", "1", "", "", "", "1"),
  row("cs-sheet-098", "others", "High pressure cooker gas", "1", "", "", "", "1"),
  row("cs-sheet-099", "others", "lower pressure cooker", "1", "", "", "", "1"),
  row("cs-sheet-100", "others", "cooker four plates", "1", "", "", "", "1"),
  row("cs-sheet-101", "others", "Rice cooker", "1", "", "", "", "1"),
  row("cs-sheet-102", "others", "bBread buscket", "2", "", "", "", "2"),
  row("cs-sheet-103", "others", "Coffee maker", "1", "", "", "", "1"),
  row("cs-sheet-104", "others", "Microwave", "1", "", "", "", "1"),
  row("cs-sheet-105", "others", "Fruit busket", "1", "", "", "", "1"),
  row("cs-sheet-106", "others", "Toaster", "1", "", "", "", "1"),
  row("cs-sheet-107", "others", "pan big", "4", "", "", "", "4"),
  row("cs-sheet-108", "others", "pan small", "2", "", "", "", "2"),
  row("cs-sheet-109", "others", "local pan", "2", "", "", "", "2"),
  row("cs-sheet-110", "others", "hot bottle themos", "3", "", "", "", "3"),
  row("cs-sheet-111", "others", "chopping board", "2", "", "", "", "2"),
  row("cs-sheet-112", "others", "Juice jug(water)", "1", "", "", "", "1"),
  row("cs-sheet-113", "others", "Serving dihes small", "3", "", "", "", "3"),
  row("cs-sheet-114", "others", "Serving dishes big", "6", "", "", "", "6"),
  row("cs-sheet-115", "others", "Kitchen dustbeen", "1", "", "", "", "1"),
  row("cs-sheet-116", "others", "Strainer", "3", "", "", "", "3"),
  row("cs-sheet-117", "others", "Bone knife", "1", "", "", "", "1"),
  row("cs-sheet-118", "others", "Knife min size", "2", "", "", "", "2"),
  row("cs-sheet-119", "others", "Knife small size", "2", "", "", "", "2"),
  row("cs-sheet-120", "others", "Serving spoon", "15", "", "", "", "15"),
  row("cs-sheet-121", "others", "Spartuller", "10", "", "", "", "10"),
  row("cs-sheet-122", "others", "Soup ledor", "5", "", "", "", "5"),
  row("cs-sheet-123", "others", "Blender", "1", "", "", "", "1"),
  row("cs-sheet-124", "others", "Tons", "10", "", "", "", "10"),
  row("cs-sheet-125", "others", "Mwiko", "2", "", "", "", "2"),
  row("cs-sheet-126", "others", 'Creater big/small', '2"1', "", "", "", '2"1'),
  row("cs-sheet-127", "others", "Laundry dustbeen", "4", "", "", "", "4"),
  row("cs-sheet-128", "others", "Washing basin", "2", "", "", "", "2"),

  row("cs-sheet-129", "staff-utensils", "Plates", "17", "", "", "", "17"),
  row("cs-sheet-130", "staff-utensils", "Spoon", "8", "", "", "", "8"),
  row("cs-sheet-131", "staff-utensils", "Themos", "1", "", "", "", "1"),
  row("cs-sheet-132", "staff-utensils", "Cups", "17", "", "", "", "17"),

  row("cs-sheet-133", "reception", "Carpet", "2", "", "", "", "2"),
  row("cs-sheet-134", "reception", "Office chairs big", "4", "", "", "", "4"),
  row("cs-sheet-135", "reception", "Office chair small", "2", "", "", "", "2"),
  row("cs-sheet-136", "reception", "Safe", "1", "", "", "", "1"),
  row("cs-sheet-137", "reception", "Computer", "2", "", "", "", "2"),
  row("cs-sheet-138", "reception", "Printer canon", "2", "", "", "", "2"),
  row("cs-sheet-139", "reception", "Order printer machine", "1", "", "", "", "1"),
  row("cs-sheet-140", "reception", "Plastic chairs", "3", "", "", "", "3"),
  row("cs-sheet-141", "reception", "Sofa seat & table", "2", "", "", "", "2"),
  row("cs-sheet-142", "reception", "A/C- total", "57", "", "", "", "57"),
  row("cs-sheet-143", "reception", "Fan", "7", "", "", "", "7"),
  row("cs-sheet-144", "reception", "Shower mixer total", "59", "", "", "", "59"),
  row("cs-sheet-145", "reception", "Wifi router", "7", "", "", "", "7"),
  row("cs-sheet-146", "reception", "Fire Extinguisher", "9", "", "", "", "9"),
  row("cs-sheet-147", "reception", "Flower pots", "8", "", "", "", "8"),
  row("cs-sheet-148", "reception", "Generator", "1", "", "", "", "1"),
  row("cs-sheet-149", "reception", "Water tank ltr 10000", "5", "", "", "", "5"),
  row("cs-sheet-150", "reception", "DSTV decorder", "1", "", "", "", "1"),
  row("cs-sheet-151", "reception", "AZAM decorder", "1", "", "", "", "1"),
  row("cs-sheet-152", "reception", "Washing machine", "2", "", "", "", "2"),

  row("cs-sheet-153", "lights", "Rooms 1st floor-small/big", "67/33", "", "", "", "67/33"),
  row("cs-sheet-154", "lights", "Room 2nd-5th floor", "200", "", "", "", "200"),
  row("cs-sheet-155", "lights", "corridor 1-5th floor", "29", "", "", "", "29"),
  row("cs-sheet-156", "lights", "balcon", "52", "", "", "", "52"),
  row("cs-sheet-157", "lights", "reception+office+store", "10", "", "", "", "10"),
  row("cs-sheet-158", "lights", "Outdoor wall lights", "12", "", "", "", "12"),
  row("cs-sheet-159", "lights", "restaurant+bar+kitn+staff", "28", "", "", "", "28"),
];
